# These are Global constants to use throughout the game

# Screen Size
SCREEN_WIDTH = 540
SCREEN_HEIGHT = 600

# Bullet values
BULLET_RADIUS = 30
BULLET_SPEED = 10
BULLET_FIRE_RATE = .5
MAX_FIRE_RATE = .05

# Shooter values
SHOOTER_RADIUS = 40
SHOOTER_SPEED = 5
SHOOTER_SIZE = 50
START_LIVES = 3
MAX_LIVES = 10

# Target values
TARGET_SPAWN_RATE = 1
TARGET_RADIUS = 13
TARGET_SPEED = -2
